# Generated by Django 3.1 on 2020-08-13 23:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_fornecedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornecedor',
            old_name='aluno',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='fornecedor',
            old_name='curso',
            new_name='produto',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
    ]
