# Generated by Django 3.1 on 2020-08-14 00:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_auto_20200813_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
