# Generated by Django 3.1 on 2020-08-14 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_auto_20200813_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='nivel',
        ),
    ]
