# Generated by Django 3.1 on 2020-08-14 00:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_auto_20200813_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='cliente',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cliente',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='loja.cliente'),
            preserve_default=False,
        ),
    ]
